/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsaCheckbox {
        /**
          * Whether the command or control is checked. Note: this behaves the way it does in React, not the way it does in HTML.
         */
        "checked": boolean;
        /**
          * Whether the checkbox is checked by default.
          * @see {@link https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#checked MDN docs}
         */
        "defaultChecked": boolean;
        /**
          * Whether the form control is disabled
          * @see {@link https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#disabled MDN docs}
         */
        "disabled": boolean;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair
          * @see {@link https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name MDN docs}
         */
        "name": string;
        /**
          * The value that will be submitted when the checkbox is checked
          * @see {@link https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#value MDN docs}
         */
        "value": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
        /**
          * `primary` or `secondary` variation
         */
        "variation": string;
    }
}
export interface DsaCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsaCheckboxElement;
}
declare global {
    interface HTMLDsaCheckboxElement extends Components.DsaCheckbox, HTMLStencilElement {
    }
    var HTMLDsaCheckboxElement: {
        prototype: HTMLDsaCheckboxElement;
        new (): HTMLDsaCheckboxElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "dsa-checkbox": HTMLDsaCheckboxElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DsaCheckbox {
        /**
          * Whether the command or control is checked. Note: this behaves the way it does in React, not the way it does in HTML.
         */
        "checked"?: boolean;
        /**
          * Whether the checkbox is checked by default.
          * @see {@link https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#checked MDN docs}
         */
        "defaultChecked"?: boolean;
        /**
          * Whether the form control is disabled
          * @see {@link https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#disabled MDN docs}
         */
        "disabled"?: boolean;
        /**
          * Name of the form control. Submitted with the form as part of a name/value pair
          * @see {@link https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#name MDN docs}
         */
        "name"?: string;
        "on_change"?: (event: DsaCheckboxCustomEvent<unknown>) => void;
        /**
          * The value that will be submitted when the checkbox is checked
          * @see {@link https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#value MDN docs}
         */
        "value"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
        /**
          * `primary` or `secondary` variation
         */
        "variation"?: string;
    }
    interface IntrinsicElements {
        "dsa-checkbox": DsaCheckbox;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dsa-checkbox": LocalJSX.DsaCheckbox & JSXBase.HTMLAttributes<HTMLDsaCheckboxElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
